### ISSUE TITLE
UE's can't connect to LimeSDR on a bandwhith 1,4Mhz

### ISSUE THREAD

**Issue by zikkuratti** [myriadrf/LimeSuite#363] opened 2022-08-05 03:09 UTC
Faced with the problem that the LimeSDR USB doesn't start registration procedure then n_prb=6 (Band 8) on prb = 50 it's work well but to me is principal 6.  using SrsRan 21.04 because 22.04 last is drop after 5 call's. Could it be some kind a calibration range problem on this software  driver level?

**Comment by 9600** [comment] 2022-08-05 07:53
It's not impossible that there is an issue in Lime Suite. However, given that many applications work just fine with far lower bandwidths, I'm more inclined to suspect the issue is in srsRAN. Hence more investigation is required and I don't think it makes sense to log an issue on this tracker just yet. 

I'm going to close this issue and suggest you post on the srsRAN list/issue tracker and perhaps MyriadRF forums, to see if anyone there has any experience with 6 prb configured.

Also just to check that you have configured with 'USE_LTE_RATES=true' before building srsRAN. Using non-standard sampling rates, which you get if you don't do this (or use pre-built packages), is likely to cause problems.

**Closed by 9600** 2022-08-05 07:53 UTC
